### PR TITLE
Use sci-hub GNSS site for OSV

### PR DESCRIPTION
**Pull request by tyler-c2s**
Some initial work towards replacing the qc.sentine1.eo.esa.int endpoint with new [scihub.copernicus.eu/gnss](https://scihub.copernicus.eu/gnss/#/home) endpoint for OSV using the [OpenSearchAPI](https://scihub.copernicus.eu/userguide/FullTextSearch) functionality.

Poked around and looked like this is the place that had the qc.sentinel1 dependency, still need to add a few bits to get this fully functional I believe. @johntruckenbrodt  let me know if I'm going in the wrong direction here.

Done / TODO:

- [x] support current querying/filtering and getting links  in `OSV.catch`
- [x] Add page support in `OSV.catch` (currently only first 10 items)
- [x] Download in same format / directory as current method (OSV.retrieve)

Additionally this endpoint seems to be very incomplete, I did not see orbit files before ~ Dec 2020 - Jan 2021 and after Feb 25th 2021, despite it being tapped as the [official source onward](https://forum.step.esa.int/t/orbit-file-timeout-march-2021/28621/39)

### CODE REVIEW

**Comment by johntruckenbrodt** [comment]
Hi @tyler-c2s! Thanks a lot for starting to work on this. Together with a colleague I have developed a package [esa_sentinel](https://github.com/johntruckenbrodt/esa_sentinel). It is dedicated to Sentinel data download but the API should be the same. Maybe there are a couple of things you might find helpful, for example the page scrolling.  
I'll merge some changes to the master branch in a short while so that all tests pass except those related to OSV download.  
I would like to move quickly on this to get a fixed version published as soon as possible. If you don't find the time please make the PR official so I can merge it and continue the work.

**Comment by tyler-c2s** [comment]
@johntruckenbrodt thanks for the tip on [ea_sentinel](https://github.com/johntruckenbrodt/esa_sentinel)! I'll take a look. I'll get started on integrating it. Do you think it's worth keeping around the old endpoint and switching to [aux.sentinel1.eo.esa.int/](https://aux.sentinel1.eo.esa.int/)? No API it seems but it does the older files that are not in the new site

**Comment by johntruckenbrodt** [comment]
Fantastic! It seems https://qc.sentinel1.eo.esa.int will not come back online so you can just delete everything related to it. If we ever end up needing it in the future we can just recover it from the git history. Keeping https://aux.sentinel1.eo.esa.int/ seems to make sense though. Optimally, the `OSV` class just falls back to it if the GNSS API does not respond. For the time being though I think you don't need to worry about it. I guess if GNSS is going to be the one and only solution it will only be a matter of days until all files are available.  
I have now merged my PR and have also introduced a timeout (24c91e8) to the OSV downloading so that the CI services don't take forever.

**Comment by tyler-c2s** [comment]
@johntruckenbrodt quick check on `OSV.retrieve()`. Is this the correct structure the OSV should be downloaded to? With the old endpoint down it's been tough to validate that I have the correct structure?

OSV Test Download

 Additionally, the files downloaded do not have the `.EOF` extension when unzipped (not sure if that is how already was implemented)

**Comment by johntruckenbrodt** [comment]
The folder structure is perfect. The zips need to look like this:  
`S1A_OPER_AUX_POEORB_OPOD_20191001T120758_V20190910T225942_20190912T005942.EOF.zip`
and need to contain one file with the EOF extension:
`S1A_OPER_AUX_POEORB_OPOD_20191001T120758_V20190910T225942_20190912T005942.EOF`

That's how SNAP needs it. Damn it, looks like we need to rename the file inside the zip.

**Comment by tyler-c2s** [comment]
> The folder structure is perfect. The zips need to look like this:
> `S1A_OPER_AUX_POEORB_OPOD_20191001T120758_V20190910T225942_20190912T005942.EOF.zip`
> and need to contain one file with the EOF extension:
> `S1A_OPER_AUX_POEORB_OPOD_20191001T120758_V20190910T225942_20190912T005942.EOF`
> 
> That's how SNAP needs it. Damn it, looks like we need to rename the file inside the zip.

Gotcha, that's go to know! Swapped the product key that is uses for the basename from 'title' to 'filename' which includes that `.EOF` and that fixed it

**Comment by tyler-c2s** [comment]
Okay think I have this in a workable state, I have to update test it looks like as it tests against a 2018 day, which is not yet in the new API. 

Done / TODO:
- [x] support current querying/filtering and getting links in OSV.catch
- [x] Add page support in OSV.catch (currently only first 10 items)
- [x] Download in same format / directory as current method (OSV.retrieve)
- [ ] Update test to recent year

**Comment by tyler-c2s** [comment]
@johntruckenbrodt is the test data incomplete for the OSV test? In `test_scene_osv` it looks like there should be 1 `POE` file to test against

**Comment by johntruckenbrodt** [comment]
Nice one, thanks for all your work!
The OSV file is downloaded with `id.getOSV(osvdir)`. The underlying method [pyroSAR.drivers.SAFE.getOSV](https://pyrosar.readthedocs.io/en/latest/pyroSAR.html#pyroSAR.drivers.SAFE.getOSV) extracts the acquisition time of the scene, adds a day on both ends, and searches for POE files in that time frame. Just searching in the frame from the S1 acquisition (start to stop) would not have returned a match. For the query on https://qc.sentinel1.eo.esa.int/ you needed a start date earlier than that of the OSV file. e.g. for a file `S1A_OPER_AUX_POEORB_OPOD_20191001T120758_V20190910T225942_20190912T005942.EOF`  
you would have to set the start date of the search to earlier than `20190910T225942`.

There seems to be some update on the available sites:  
https://forum.step.esa.int/t/orbit-file-timeout-march-2021/28621/60. Let's see what happens next week.

**Comment by system123** [comment]
What is still outstanding to get this finalized and merged in?

**Comment by johntruckenbrodt** [comment]
Okay it seems the download is now working but one test still fails. One assertion fails where 221 RES files are found by `OSV.catch` instead of 0 (see the log of the CI service builds). @tyler-c2s is in the US so he will likely not see this right away. I will get into this in about 1.5 hours unless you would like to do it @system123 ;-). If all goes well I can publish a new version later today.

**Comment by system123** [comment]
I can take a look at it, it seems the search is happening over the entire period of S1 – which makes sense that there are 221 OSV results then. I think the end date was meant to be specified as the period prior to the first acquisition.

**Comment by johntruckenbrodt** [comment]
Nice! Here's what happens in detail in this `test_scene_osv`:

- identify scene `S1A_IW_GRDH_1SDV_20150222T170750_20150222T170815_004739_005DD8_3768.zip`
- get OSV files with `id.getOSV` for the time range 20150221T170750 to 20150223T170750 (plus/minus one day of scene acquisition start).
- search for RES scenes in the time range of existing POE files (downloaded in the last step)

The number of files should be 0, because there are already locally existing POE files so there is no need to download RES files. RES files are only supposed to be found when there is no POE file for the time frame in question available yet.

**Comment by johntruckenbrodt** [comment]
Ah of course. The POE file is not found and can thus not be downloaded. There are no local POE files so it is like you said @system123, the whole range is searched from 2014-07-31 until today. There should be much more files than just 221 so there are a few online (20201201 to 20210216) but by far not all.  
So long story sort, I think the code works as it should, but the website is not fully operational. Worst case scenario could be that all RES files will be available before the POE files causing the test to download the full archive of RES files.

**Comment by system123** [comment]
@johntruckenbrodt We could update the test data for this test to a newer image that currently has a POE file in the catalog. Ultimately we'd want to avoid having the full RES archive downloaded as it's about 18 GB. If that sounds like a viable solution I can include one of the Feb 2021 images I have in the test data.

**Comment by johntruckenbrodt** [comment]
@system123, sounds good! This is most straight forward to finish the development. I will remove the new Feb '21 image once the other one works again to save some space but for now an additional 1-2 MB don't hurt.

**Comment by system123** [comment]
The tests are now passing locally, I've created #133 to capture these changes and the updated tests as I cannot modify this PR directly.

**Comment by johntruckenbrodt** [comment]
Thanks @tyler-c2s and @system123 for this important fix. Let's hope that the new site will soon be fully operational and we can go on with routine processing.

**Comment by tyler-c2s** [comment]
@johntruckenbrodt , @system123 thanks for all the support!

**Pull request merged**
