### PR TITLE
Feature/new suffixes

### PR DESCRIPTION
**Pull request by renedacosta**
I've Added the following SNAP elements to the suffix list:
TOPSAR-Split, TOPSAR-Deburst, SnaphuExport, Interferogram, GoldsteinPhaseFiltering, Back-Geocoding

These were missing causing an error when running my snap workflow using pyroSAR

### CODE REVIEW

**Comment by johntruckenbrodt** [comment]
Hi @renedacosta,
thanks a lot for the PR! I have lately changed the mechanism of how suffices are handled. They are now delivered in a new file [snap.suffices.properties](https://github.com/johntruckenbrodt/pyroSAR/blob/master/pyroSAR/snap/data/snap.suffices.properties).
These suffices were directly extracted from the SNAP source code with [collect_suffices.py](https://github.com/johntruckenbrodt/pyroSAR/blob/master/pyroSAR/snap/data/collect_suffices.py).
However, for some reason not all the nodes you need are in the list:
- [x] Back-Geocoding
- [x] GoldsteinPhaseFiltering
- [x] Interferogram
- [ ] SnaphuExport
- [x] TOPSAR-Deburst
- [ ] TOPSAR-Split

I'll have a look what's going on and give you an update.
So while this PR is unfortunately not needed you can leave it open for now so we can exchange ideas about this.

Cheers,
John

**Comment by johntruckenbrodt** [comment]
Hi @renedacosta,
I found the issue. `SnaphuExport` and `TOPSAR-Split` don't have default suffices in SNAP. The new pyroSAR mechanism is designed to also just not apply a suffix (and not fail) if it is not contained in the list.
On first import of pyroSAR.snap, a configuration file `config.ini` is created in a user's home directory under `.pyrosar`. You can modify the suffix section to apply your own custom suffices.
Cheers

**Comment by renedacosta** [comment]
Hi @johntruckenbrodt 

Thanks, this new mechanism sounds indeed more robust will test it out.
Is it already incorporated in the latest version ?

Cheers
Rene

**Comment by johntruckenbrodt** [comment]
Hi @renedacosta,
thanks for the feedback. The mechanism is already part of version 0.11.
I am closing this for now.
Cheers,
John

**Pull request closed without merging**
