### PR TITLE
drivers.py: Add BEAM_DIMAP handler class for .dim files

### LINKED ISSUE #176: Feature: execute graphs with beam-dimap input
Hi all,
I'm using pyroSAR to create, group, and then execute a graph via SNAP, the last of which via `gpt` from `pyroSAR.snap.auxil`. It seems to me that this operation fails if I want to use `.dim` BEAM-DIMAP formatted intermediate products from SNAP as inputs to my workflow (It's raising `RuntimeError: data format not supported`). The same graph also fails in the SNAP graph tool, but works fine if I execute it via `gpt` in the command line.

From what I've seen in the code, I'm guessing that I can only execute graphs with pyroSAR that contain compressed formats (e.g. SAFE .zips) in their `READ` nodes?

I also wanted to ask if this might be a feature in which more people might be interested / that would be easy to implement?

### PR DESCRIPTION
**Pull request by pbrotoisworo**
This adds a new Handler class to handle `.dim` files which are used by SNAP software.

Fixes #176.

Things to note:

- getCorners() may not be needed under `BEAM_DIMAP` because I extracted the `meta['corners']` data from `gdalinfo` from the raster data. Or perhaps I should still include this under `BEAM_DIMAP.getCorners()`?
- Only tested with Sentinel-1 data (I don't have access to other sensors)
- Added flexibility for datasets with no CRS data.
- Tries to get all available metadata from the .dim first before loading the raster in GDAL.

Here is the sample output when using a terrain corrected .dim file with `from pyroSAR import identify`:

```
pyroSAR ID object of type BEAM_DIMAP
acquisition_mode: IW
cycleNumber: 113
frameNumber:
lines: 3176
orbit: ASCENDING
orbitNumber_abs: 17393
orbitNumber_rel: 171
polarizations: ['VV']
product: Sentinel-1 IW Level-1 SLC Product
projection: +proj=longlat +ellps=WGS84 +no_defs
samples: 2771
sensor: SENTINEL-1A
spacing: (0.0003772924193301991, -0.0003772924193301991)
start: 09-JUL-2017 11:24:23.927343
stop: 09-JUL-2017 11:24:40.803460
```

Let me know what you think @johntruckenbrodt. Hopefully I got the structure of your software right.

### CODE REVIEW

**Comment by johntruckenbrodt** [comment]
Hi @pbrotoisworo. Looks pretty good already. Here's a quick test you can run to test whether everything is working as expected. It converts an arbitrary Sentinel-1 scene to BEAM-DIMAP and compares all standardized object attributes of the original and the converted scene.
```python
import os
from pyroSAR.drivers import __LOCAL__, identify
from pyroSAR.snap.auxil import parse_recipe, parse_node
from pyroSAR.snap import gpt

grd = 'S1A_IW_GRDH_1SDV_20180101T170648_20180101T170713_019964_021FFD_DA78.zip'
dimap = grd.replace('.zip', '.dim')
out_wf = 'workflow.xml'
tmpdir = os.getcwd()

if not os.path.isfile(out_wf):
    workflow = parse_recipe('blank')
    
    read = parse_node('Read')
    workflow.insert_node(read)
    read.parameters['file'] = grd
    read.parameters['formatName'] = 'SENTINEL-1'
    
    write = parse_node('Write')
    workflow.insert_node(write)
    write.parameters['file'] = dimap
    write.parameters['formatName'] = 'BEAM-DIMAP'
    
    workflow.write(outfile=out_wf)

if not os.path.isfile(dimap):
    gpt(xmlfile=out_wf, tmpdir=tmpdir)

scene1 = identify(grd)
scene2 = identify(dimap)

for item in __LOCAL__:
    print(item)
    assert getattr(scene1, item) == getattr(scene2, item)
```

**Comment by pbrotoisworo** [comment]
Ah, this is exactly what I was looking for. I wasn't too familiar with what the metadata looked like exactly. Thanks!

**Comment by pbrotoisworo** [comment]
Hi @johntruckenbrodt ,

The latest commit passed the assertion tests using your test code so the metadata format and styling matches the `SAFE` class now. I've managed to extract all the core metadata information from the `.dim ` file so I removed the code from `gdalinfo()`. However, these functions still exist in `BEAM_DIMAP`. Would it be better to remove them or just leave them empty?

**Comment by johntruckenbrodt** [comment]
Great! You can just remove the `gdalinfo` method if you like. It is already implemented in the `ID` class so does not have to be overridden. 
However, the `self.meta['corners']` attribute is missing now. If possible then this information is also read from the `.dim` file (it is faster than opening a file with GDAL), but otherwise you can bring back the functionality from `gdalinfo`.
If you have an attribute `self.meta['corners']` then `getCorners` should just look like this:
```python
  def getCorners(self):
      return self.corners
```

**Comment by pbrotoisworo** [comment]
After some experimenting I've managed to calculate the corners it from IMAGE_TO_MODEL_TRANSFORM attribute in the latest commit. This attribute doesn't follow the GDAL geotransform format so I had to reorganize it. In my testing, the corner values still matches the values when you calculate `img.GetGeotransform()` using GDAL so it should be fine and should cut down on the loading time.

I think this attribute only exists if the product is terrain corrected.

**Comment by pbrotoisworo** [comment]
Ah that's a good catch.. Sorry, I had too much focus on the `Coordinate_Reference_System` and `Geoposition` attributes I completely overlooked these attributes. I will check these out now.

**Comment by pbrotoisworo** [comment]
The latest commit now utilizes this metadata to calculate `self.meta['corners']`.

> I had a brief look into the .dim file created in the example above. Don't you have this entry in your test file?:
> 
> ```
> <MDATTR name="first_near_lat" desc="" unit="deg" type="float64" mode="rw">45.432472229003906</MDATTR>
> <MDATTR name="first_near_long" desc="" unit="deg" type="float64" mode="rw">9.8927412660746</MDATTR>
> <MDATTR name="first_far_lat" desc="" unit="deg" type="float64" mode="rw">45.834449768066406</MDATTR>
> <MDATTR name="first_far_long" desc="" unit="deg" type="float64" mode="rw">13.185704011443109</MDATTR>
> <MDATTR name="last_near_lat" desc="" unit="deg" type="float64" mode="rw">46.9346923828125</MDATTR>
> <MDATTR name="last_near_long" desc="" unit="deg" type="float64" mode="rw">9.498409767529125</MDATTR>
> <MDATTR name="last_far_lat" desc="" unit="deg" type="float64" mode="rw">47.33588409423828</MDATTR>
> <MDATTR name="last_far_long" desc="" unit="deg" type="float64" mode="rw">12.88226081168404</MDATTR>
> ```

**Comment by johntruckenbrodt** [comment]
Awesome! I think we got it now. I will merge it into a development branch to do a few last edits and then it is good to go.
Thanks a lot Panji. Maraming salamat po.

**Comment by pbrotoisworo** [comment]
Thank you so much for the help @johntruckenbrodt . Looking forward to your update!

**Comment by johntruckenbrodt** [comment]
@pbrotoisworo this is now part if the new version 0.16.0. Welcome to the developer team!

**Pull request merged**
