### PR TITLE
Topsarsplit node

### PR DESCRIPTION
**Pull request by vpolimenov**

### CODE REVIEW

**Comment by johntruckenbrodt** [comment]
Hi,
thanks a lot for the PR! I don't know if there is more to come, but you might want to check out PR #109. This will make it possible to automatically parse nodes and their default values without storing the XML files in the source code.  
I'll go though the nodes you've added and see whether everything I've added works as expected.
Cheers, John

**Comment by vpolimenov** [comment]
ah nice! Let me know and I can either squash all those commits or just close the PR :+1:

**Comment by johntruckenbrodt** [comment]
Hi. These node XML files should not be needed anymore with the new parsing approach. I checked all your nodes and they work fine. So you can just close the PR.  
It would be really awesome though if you would add your recipe as a new function to [snap.util](https://github.com/johntruckenbrodt/pyroSAR/blob/master/pyroSAR/snap/util.py) ;-)

**Comment by johntruckenbrodt** [comment]
closing this for now because the addressed problem was already solved in version 0.11.

**Pull request closed without merging**
